#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

kakfa_ready() {
python << END

import os
import sys
from kafka import KafkaConsumer
try:
    KAFKA_HOST = os.environ.get('KAFKA_HOST', 'kafka')
    KAFKA_PORT = os.environ.get('KAFKA_PORT', '9092')
    c = KafkaConsumer(bootstrap_servers=["${KAFKA_HOST}:${KAFKA_PORT}"])
    c.close()
except Exception:
    sys.exit(-1)
sys.exit(0)
END
}
until kakfa_ready; do
  >&2 echo 'Waiting for Kafka to become available...'
  sleep 1
done
>&2 echo 'Kafka is available'

exec "$@"
