#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

kakfa_ready() {
python << END

import sys
from kafka import KafkaConsumer
try:
    c = KafkaConsumer(bootstrap_servers=["${KAFKA_HOST}:${KAFKA_PORT}"])
    c.close()
except Exception:
    sys.exit(-1)
sys.exit(0)
END
}
until kakfa_ready; do
  >&2 echo 'Waiting for Kafka to become available...'
  sleep 1
done
>&2 echo 'Kafka is available'

exec "$@"
